image: ubuntu

stages:
 - build

job:Abache2_deploy:
  stage: build
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update -yqq
    - apt-get install apache2 curl -yqq
    - apache2ctl configtest
    - curl http://localhost
