image: ubuntu

stages:
 - build

job:Abache2_deploy:
  stage: build
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get update -yqq
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get install nginx curl -yqq
    - nginx -t && service nginx reload
    - curl --ipv4 http://localhost
